### PR TITLE
Day 4 notebook-data changes

### PR DESCRIPTION
**Pull request by cemsaz**
**CV Dataset**
- Downsampled the dataset. 1000 images training and 200 validation, renamed: EMBK-NLP-GLUONCV.zip
- Created train and val folders, easier to use with gluoncv

**Notebooks:**
 Minor typo fixes, run-time and equations addition and removing extra plots/prints.
- **EMBK-NLP-DAY4-AUTOGLUON-CV-NB.ipynb:** Removed
- **EMBK-NLP-DAY4-GLUON-CV-TRAIN-NB.ipynb:** Newly added. Trains alexnet on the downsampled dataset
- **EMBK-NLP-DAY4-GLUON-CV-NB.ipynb:** Kernel die problem fixed (filename issue). Added description to classification results

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bwerness** [comment]
Hi Cem, what is the reason you are removing the AutoGluon CV notebook?  Runtime?

**Comment by cemsaz** [comment]
Yes, run time and plus it throws error with the t3.large instance, runs fine with gpu.

**Comment by bwerness** [comment]
I would leave it in just with a note that it doesn't run on T3, just since it makes some of these problems so easy to build a prototype.

**Comment by cemsaz** [comment]
Added the Autogluon CV notebook back

**Pull request merged**
